<a href="https://colab.research.google.com/github/MFahadHussain/MachineLearning/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Assignment

This assignment covers a wide range of NumPy functionalities, from basic array creation to advanced operations like linear algebra. It is suitable for undergraduate students who are new to NumPy or need practice with its core features.


Instructions
- Complete all the tasks in this Jupyter Notebook.
- Write your code in the provided code cells.
- Test your code to ensure it works as expected.
- Submit your completed notebook.

#### Submission
- Save your Jupyter Notebook.
- Submit the notebook file with your solutions.

Enter your name: Fahad Hussain
Program: BS Data Science
Group:B

Task 1: Import NumPy <br />
Import the NumPy library and use the alias np.

In [ ]:
import numpy as np

Task 2: Create Arrays
- Create a 1D array with the numbers 1 through 10.
- Create a 2D array of shape (3, 3) with all elements set to 1.
- Create a 3D array of shape (2, 2, 2) with random integers between 0 and 100.

In [ ]:
D1=np.arange(1,11)
D2=np.ones((3,3))
D3=np.random.randint(0,100,(2,2,2))
print(D1,D2,D3)

[ 1  2  3  4  5  6  7  8  9 10] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[[69 81]
  [96 20]]

 [[60 14]
  [40 67]]]


Task 3: Array Operations
- Given the array arr = np.array([1, 2, 3, 4, 5]), multiply each element by 10.
- Compute the sum of all elements in the array.
- Compute the mean and standard deviation of the array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr10=arr*10
print(arr10)

[10 20 30 40 50]


Task 4: Array Indexing and Slicing
- Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract the second row.
- Extract the first two columns.
- Extract the subarray [[2, 3], [5, 6]].

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1])
print(arr[:,0:2])
print(arr[1:,1:])

[4 5 6]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]


Task 5: Reshape and Transpose
- Reshape the array arr = np.arange(1, 13) into a 3x4 matrix.
- Transpose the resulting matrix.

In [ ]:
arr = np.arange(1, 13)
print(arr.reshape(3,4))
print(arr.reshape(3,4).T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Task 6: Mathematical Functions
- Compute the element-wise square root of the array arr = np.array([1, 4, 9, 16, 25]).
- Compute the exponential of each element in the array arr = np.array([1, 2, 3]).
- Compute the dot product of a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]).

In [ ]:
arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))
arr1 = np.array([1, 2, 3])
print(np.exp(arr1))

[1. 2. 3. 4. 5.]
[ 2.71828183  7.3890561  20.08553692]


Task 7: Advanced Operations
- Create a 5x5 identity matrix.
- Stack two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.
- Split the array arr = np.arange(1, 11) into 3 equal parts.

In [ ]:
a=np.identity(5)
print(a)
b=np.array([1, 2, 3])
c=np.array([4, 5, 6])
print(np.vstack((b,c)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2 3]
 [4 5 6]]


Task 8: Boolean Indexing
- Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), extract all elements greater than 5.
- Replace all elements less than 5 with 0.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[arr>5])
arr[arr<5]=0
print(arr)

[ 6  7  8  9 10]
[ 0  0  0  0  5  6  7  8  9 10]


Task 9: Linear Algebra
- Compute the determinant of the matrix A = np.array([[1, 2], [3, 4]]).
- Compute the inverse of matrix A.
- Solve the system of linear equations:
  - 2x+3y=8
  - x−y=1

In [ ]:
A=np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))
print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


Task 10: Challenge Problem
- Create a 10x10 array where the border elements are 1 and the inner elements are 0.
- Normalize the array arr = np.random.randint(0, 100, size=(5, 5)) so that all values lie between 0 and 1.

In [ ]:
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)
A=np.random.randint(0, 100, size=(5, 5))
print(A)
print((A-np.min(A))/(np.max(A)-np.min(A)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[62 91 56 60 39]
 [63 15 98  0 52]
 [63 18 80 98 91]
 [83 35 99 90 64]
 [95 51 74 82 38]]
[[0.62626263 0.91919192 0.56565657 0.60606061 0.39393939]
 [0.63636364 0.15151515 0.98989899 0.         0.52525253]
 [0.63636364 0.18181818 0.80808081 0.98989899 0.91919192]
 [0.83838384 0.35353535 1.         0.90909091 0.64646465]
 [0.95959596 0.51515152 0.74747475 0.82828283 0.38383838]]


Task 11: Make a function and perform the following in it.

   **1: Print the given data in a DataFrame**
    
   **2: Print the first 3 rows**
   
   **3: Print the last 3 rows**
   
   data = { <br />
    'A': [1, 2, 3, 4, 5, 6], <br />
    'B': [7, 8, 9, 10, 11, 12],<br />
    'C': [13, 14, 15, 16, 17, 18] <br />
}

In [ ]:
import pandas as pd
A=np.array([1, 2, 3, 4, 5, 6])
B=np.array([7, 8, 9, 10, 11, 12])
C=np.array([13, 14, 15, 16, 17, 18])

print(pd.DataFrame({'A':A,'B':B,'C':C}))

print(pd.DataFrame({'A':A,'B':B,'C':C}).head(3))

print(pd.DataFrame({'A':A,'B':B,'C':C}).tail(3))

   A   B   C
0  1   7  13
1  2   8  14
2  3   9  15
3  4  10  16
4  5  11  17
5  6  12  18
   A  B   C
0  1  7  13
1  2  8  14
2  3  9  15
   A   B   C
3  4  10  16
4  5  11  17
5  6  12  18


Task 12: Make a function and perform the following functions.**

   **1: Perform the mathematical function +50 to the given numpy array**
    
   **2: Add an element at the index position [3],[6],[8] in the array**
    
   **3: Check the shape of the array**
   
   array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array+50)
array=np.append(array,11)
print(array)

[51 52 53 54 55 56 57 58 59 60]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
array.shape

(11,)

In [ ]:
np.ndim(array)

1